### ISSUE TITLE
Запросы на улучшение 1

### ISSUE THREAD

**Issue by guzszisvww** [henrypp/hostsmgr#10]
Извиняюсь, что 5 штук в одном запросе, но они маленькие.

1. example.bat
Если запускается из папки с пробелами или плюсами, то не работает.
Предалагаю так: 
`"%~dp0hostsmgr.exe" -ip 0.0.0.0 -os win -path "%~dp0example_hosts"`

2. В **Readme.txt** добавить описание назначения и формата файлов **sources.txt** , **userlist.txt** , **whitelist.txt** .

3. В выводе программы писать полные пути файлов, чтобы не было путаницы, с какими файлами идёт работа.
Пример:
```
Sources: C:\hostsmgr-1.2-bin\sources.txt
Userlist: C:\hostsmgr-1.2-bin\userlist.txt
Whitelist: C:\hostsmgr-1.2-bin\whitelist.txt
```

4. Пустые строки в **sources.txt** учитываются. Зачем? Пользователь вставил пустые строки, чтобы выделить группы взаимосвязанных источников.

5. При скачивании файлов происходит полная загрузка процессора. Нельзя ли с этим что-то сделать?

**Comment by henrypp** [comment]
1. done
2. done
3. done
4.  пустые строки и комменты не учитываются!
5. исправлено
