### ISSUE TITLE
Symptoms of computer failure. The Internet is not working.

### ISSUE THREAD

**Issue by oklokl** [henrypp/hostsmgr#12]
Microsoft Windows [Version 10.0.19043.1055] home kr 64bit Insider
hostsmgr 64bit Version: 2.1.1

![3](https://user-images.githubusercontent.com/1571600/121980462-f1454700-cdc6-11eb-98cf-fa4ca15c70b4.png)

The message above came out.
So I added an exception from the vaccine and ran it again.
ok
success

I did it like this.
1 Edit sample.bat
@echo off
"%~dp0hostsmgr.exe" -ip 0.0.0.0 -os win -path "C:\Windows\System32\drivers\etc\HOSTS"
rem "%~dp0hostsmgr.exe" -ip 0.0.0.0 -os linux -path ".\hosts_linux"
pause

But my computer is
ipconfig /flushdns
The dns cannot be renewed. It keeps stopping.
Dnscache cpu 27% memory 120m (Megabytes) ~ Continuously increasing

So I'm going into msconfig safe mode and...
Delete hosts file.
I rebooted normally.

In my case, run the sample.bat file without editing it. Windows worked fine even after booting. And the HOSTS file has not been changed. The hosts_windows file was created without an error.

@echo off
"%~dp0hostsmgr.exe" -ip 0.0.0.0 -os win -path ".\hosts_windows"
rem "%~dp0hostsmgr.exe" -ip 0.0.0.0 -os linux -path ".\hosts_linux"
pause
(Do I have to use it without modification to operate normally? Does my system apply?)

but
When registering a hosts_windows file by renaming it to a HOSTS file. The above symptoms have occurred again.

:(

https://youtu.be/ZIxJV7W6XXo
My computer symptoms.
The Windows taskbar has stopped. (Everything can't work.)

![4](https://user-images.githubusercontent.com/1571600/121981685-18047d00-cdc9-11eb-89b4-3a4df8a9df41.png)
My Windows taskbar if normal

Thank you.

**Comment by henrypp** [comment]
> The dns cannot be renewed. It keeps stopping.
> Dnscache cpu 27% memory 120m (Megabytes) ~ Continuously increasing

This is a Windows-only `DnsCache` service issue... Linux, Android, Mac does not have this problem.

[Large hosts file causes networking issues in Windows 10](https://tinyapps.org/blog/201809300700_large_hosts_file.html)

https://github.com/StevenBlack/hosts/issues/56#issuecomment-169406609

Possible solution:
- Disable `DnsCache` service
- Install `dnscrypt` via [SimpleDnsCrypt](https://github.com/bitbeans/SimpleDnsCrypt/releases). This is only UI.
- Update manually to the latest [dnscrypt](https://github.com/DNSCrypt/dnscrypt-proxy/releases) service.
- No more problems from dnscache windows service.
