### ISSUE TITLE
Counter of enabled source files during downloads

### ISSUE THREAD

**Issue by woolyss** [henrypp/hostsmgr#2]
Hello Henry,

It could be nice if **hostsmgr.exe** enabled counts source files during downloads.

For example, in my **sources.txt**, I put few links in comment like that:

```
# http://hosts-file.net/ad_servers.txt
http://someonewhocares.org/hosts/zero/hosts
# http://winhelp2002.mvps.org/hosts.txt
http://adblock.gjtech.net/?format=hostfile
```

**hostsmgr.exe** displays 4 sources.
(like on your screenshot, it is always 16 sources http://www.henrypp.org/images/hostsmgr.jpg even if few links are commented)
But it will be easier to see real sources used. In my case: 2 sources.

And other thing: is it is possible to see the list of urls and their result, in the windows?
Imagine  in the windows:

```
Please wait...
http://someonewhocares.org/hosts/zero/hosts --> ok
http://adblock.gjtech.net/?format=hostfile --> bad content
```

Anyway, you created a powerful tool to update the **hosts** file !

**Comment by henrypp** [comment]
fixed

**Comment by ghost** [comment]
Thanks a lot. Well done! ;)
