### ISSUE TITLE
False positive detected by Avira Antivirus

### ISSUE THREAD

**Issue by woolyss** [henrypp/hostsmgr#3]
False positive detected by Avira Antivirus about x64 hostsmgr64.exe v1.1  :/
(Nothing about x86 hostsmgr64.exe v1.1 ; and all versions v1.0)
- https://www.virustotal.com/en/file/791cfdf38c8215432a80e8e115e889e6f9ce388d50719ea160a6ac91ade448cb/analysis/1473790474/
- https://www.metadefender.com/#!/results/file/8d473f42cf9643e7b9a9cd976d9a9215/regular/analysis
- http://r.virscan.org/report/5e7712c09e303e554f0df3e3a9ebaa41
- https://virusscan.jotti.org/en-US/filescanjob/svw0vipqwg

**Comment by ghost** [comment]
And an other remark nothing to do with this issue:
You forgot to add sources.txt, userlist.txt, whitelist.txt in 32/ and 64/ folders.

Regards
