### ISSUE TITLE
What's the purpose of hostsmgr.ini?

### ISSUE THREAD

**Issue by ghost** [henrypp/hostsmgr#5]
Hi,
I'm running hostsmgr 1.1 flawlessly on Windows 7SP1.

I understand and use sources.txt, userlist.txt and whitelist.txt (the latter with my addresses and the "joke" removed of course!).

Having been a long time user of the famous HostsManager application I prefer the approach of this Hostsmgr by far. Compact, well-thought, flawless.

Yet I don't understand the purpose of the hostsmgr.ini file. Mine remains at 0 byte here. Is this file to be edited? I don't dig it as you see!

Anyway many thanks henrypp for this nice little gem.

**Comment by henrypp** [comment]
Nothing. You can delete this file.

**Comment by ghost** [comment]
OK! Thanks.
I like, need to understand, even when there's no problem :)

If it weren't for Softpedia I might have never heard of Hostsmgr. I'll spread my word about this neat application because it fits in a major area of computing, that of privacy and security served by the HOSTS file, itself served by Hostsmgr.

All the best!

**Comment by henrypp** [comment]
@zymase, thank you!
