### ISSUE TITLE
Release file empty?

### ISSUE THREAD

**Issue by NuclearPhoenixx** [henrypp/hostsmgr#6]
For me it seems like the release file "hostsmgr-1.1-bin.zip" is completely empty except for one folder named "32". Downloaded via latest Firefox and unzipped with 7zip.

**Comment by henrypp** [comment]
Used 7-zip too. All files are exists.

![7zip](https://user-images.githubusercontent.com/3902025/32645574-1194af98-c612-11e7-97bf-31e2c1c53962.png)

**Comment by NuclearPhoenixx** [comment]
Nevermind, seems to work again.
